services:
  caddy:
    image: caddy:alpine
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile



  inbucket:
    environment:
      INBUCKET_MAILBOXNAMING: "full"
    image: inbucket/inbucket
    ports:
      - 3900:9000
      - 3250:2500
      - 3110:1100
    restart: "no"

  redis:
    image: redis:alpine
    ports:
      - "3325:6379"
    volumes:
      - "redis_persist:/data"

  postgres:
    environment:
      POSTGRES_DB: backsy_dev
      POSTGRES_USER: backsy
      POSTGRES_PASSWORD: backsy
    ports:
      - 3323:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backsy -d backsy_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_persist:/var/lib/postgresql/data
    image: postgres:15-alpine
    restart: "no"

  adminer:
      image: adminer:latest
      environment: 
          ADMINER_DEFAULT_SERVER: postgres
          ADMINER_DESIGN: galkaev
      ports: 
        - 3324:8080

  postgres-migrate:
    environment:
      POSTGRES_DB: backsy_dev
      POSTGRES_USER: backsy
      POSTGRES_PASSWORD: backsy
    ports:
      - 3326:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backsy -d backsy_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:15-alpine
    restart: "no"

volumes:
  postgres_persist:
  redis_persist: