type User {
  id: ID!
  username: String!
  email: String!
}

type Query {
  user(id: ID!): User!
  users: [User!]!
}

input NewUserInput {
  username: String!
  email: String!
}

type Mutation {
  createUser(input: NewUserInput!): User!
}
