package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/jeffreycharters/trailshark/backsy/ent"
	"github.com/jeffreycharters/trailshark/backsy/pkg/ulid"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input NewUserInput) (*ent.User, error) {
	return r.DB.User.Create().
		SetEmail(input.Email).
		Save(ctx)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id ulid.ID) (*ent.User, error) {
	return r.DB.User.Get(ctx, id)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*ent.User, error) {
	return r.DB.User.Query().All(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
