type Mutation {
	createUser(input: NewUserInput!): User!
}
input NewUserInput {
	username: String!
	email: String!
}
type Query {
	user(id: ID!): User!
	users: [User!]!
}
type User {
	id: ID!
	username: String!
	email: String!
}
